"""1

Revision ID: 272885860a57
Revises: 288a72610cf3
Create Date: 2024-01-10 14:48:39.209156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272885860a57'
down_revision = '288a72610cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_receiver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['client_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_receiver_id_fkey', 'users', ['receiver_id'], ['client_id'])

    # ### end Alembic commands ###
